pipecleaner: Don't error on external task files
The "integration test" pipeline added in the preceding commit defines a task
whose config is defined in the separate repo being tested. This fails
pipecleaner because it attempts to load the task file from this repo:

    ➜  paas-release-ci git:(57d1750) make lint_concourse
    ./scripts/pipecleaner.py --fatal-warnings pipelines/*.yml
    Traceback (most recent call last):
      File "./scripts/pipecleaner.py", line 264, in <module>
        errors = p.validate(filename)
      File "./scripts/pipecleaner.py", line 41, in validate
        return self.check_pipeline(data)
      File "./scripts/pipecleaner.py", line 152, in check_pipeline
        item['config'] = self.load_pipeline(item['file'])
      File "./scripts/pipecleaner.py", line 44, in load_pipeline
        raw = open(filename).read()
    IOError: [Errno 2] No such file or directory: 'pr/ci/integration.yml'
    make: *** [lint_concourse] Error 1

Fix this by telling pipecleaner to assume an empty task config for any tasks
that use `file` where the specified file cannot be loaded. The default value
for `ignore_missing` means that this doesn't affect the initial pipeline load:

    ➜  paas-release-ci git:(feature/140847887-integration_test_pipelines) ./scripts/pipecleaner.py --fatal-warnings does_not_exist.yml
    Traceback (most recent call last):
      File "./scripts/pipecleaner.py", line 269, in <module>
        errors = p.validate(filename)
      File "./scripts/pipecleaner.py", line 40, in validate
        data = self.load_pipeline(filename)
      File "./scripts/pipecleaner.py", line 45, in load_pipeline
        raw = open(filename).read()
    IOError: [Errno 2] No such file or directory: 'does_not_exist.yml'